### ISSUE TITLE
Mod Browser download is broken

### ISSUE THREAD

**Issue by NightKev** [Agrair/InvTweaks#1]
Currently it points to `https://github.com/Agrair/VerifyWalls/releases/download/v1.2.0.1/InvTweaks.tmod` instead of `https://github.com/Agrair/InvTweaks/releases/download/v1.0.0.2/InvTweaks.tmod`.

**Comment by Agrair** [comment]
Thanks for actually putting this up on GitHub! However, it should be fixed by now. Sorry for the slight delay. @NightKev
